Llama-3-Instruct-8B-SimPO:
  completions_kwargs:
    batch_size: 900
    do_sample: true
    max_new_tokens: 4096
    model_kwargs:
      torch_dtype: bfloat16
    model_name: llama-3-1b-instruct-simpo-v1-with-lora-1.0e-6-beta-8.0-gamma-0.1
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.9
    top_p: 1.0
  fn_completions: vllm_local_completions
  pretty_name: Llama-3.2-1B-Instruct-SimPo-Beta-8.0-gamma-0.1-lr-1.0e-6
  prompt_template: /h/snajafi/SimPO/eval/alpacaeval2/templates/llama3.txt
  link: /home/saeednjf/nearline/rrg-afyshe/saeednjf/mmpo-experiments/simpo-runs/llama-3-1b-instruct-simpo-v1-with-lora-1.0e-6-beta-8.0-gamma-0.1
