Llama-3-Instruct-1B-SLiC-hf:
  completions_kwargs:
    batch_size: 16
    max_new_tokens: 4096
    model_kwargs:
      dtype: bfloat16
    model_name: SaeedNajafi/llama-3-1b-instruct-slic-hf-v1-with-lora-1.0e-6-lambda-1.0-sigma-0.5_full_model
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.9
    top_p: 1.0
  fn_completions: vllm_local_completions
  pretty_name: llama-3-1b-instruct-slic-hf-v1-with-lora-1.0e-6-lambda-1.0-sigma-0.5
  prompt_template: /h/snajafi/SimPO/eval/alpacaeval2/templates/llama3.txt
