# Model arguments
model_name_or_path: /model-weights/Meta-Llama-3-8B-Instruct
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  /scratch/ssd004/scratch/snajafi/datasets/llama3-ultrafeedback-armorm/data: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 2.5
gamma_beta_ratio: 1.4
do_eval: true
evaluation_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: simpo-exps-lora
learning_rate: 1.0e-6
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 10
optim: adamw_8bit
output_dir: /scratch/ssd004/scratch/snajafi/vector-backup/simpo-experiments/llama-3-8b-instruct-simpo-v3-with-lora
run_name: llama-3-8b-instruct-simpo-v3-with-lora
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
use_peft: true
lora_r: 64
lora_alpha: 64
lora_dropout: 0.1
