# Model arguments
model_name_or_path: /model-weights/Llama-3.2-1B-Instruct
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  /scratch/ssd004/scratch/snajafi/datasets/llama-3.2-1b-instruct-data: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 4

# SimPOTrainer arguments
bf16: true
beta: 8.0
gamma_beta_ratio: 0.1
do_eval: true
evaluation_strategy: steps
eval_steps: 50
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: simpo-exps-lora
learning_rate: 1.0e-6
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 3
optim: adamw_8bit
output_dir: /scratch/ssd004/scratch/snajafi/vector-backup/simpo-experiments/llama-3-1b-instruct-simpo-v1-with-lora-1.0e-6-beta-8.0-gamma-0.1
run_name: llama-3-1b-instruct-simpo-v1-with-lora-beta-8.0-gamma-0.1-lr-1.0e-6
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
use_peft: true
lora_r: 64
lora_alpha: 64
lora_dropout: 0.1
